# This workflow generates documentation (PDFs, interactive BOMs, board images). The
# The version number and date of the design is automatically updated in the schematic
# file and on the PCB. The version number is set via an environment variable
# and by default is `pre-release` since this runs outside of the release process
# so there's no formal release number to use.

# To use this workflow in your own repo you need to edit the timezone in the environment variables in the env: section
# below.
name: "KiBot - Generate Schematic Outputs"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

jobs:
  Documentation:
    env:
      # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
      Timezone: Australia/Perth
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
      # Set this to the version to include in the schematic and PCB. Since this
      # script runs outside of the release process it can't pull a version
      # number automatically from GitHub.
      Version: pre-release
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the base project name
      - name: Get KiCad project name
        id: project_name
        run: echo "::set-output name=project_name::$(find ./hardware -iname *.kicad_pro -execdir basename {} .kicad_pro ';')"

      # Get the current date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Do a string replacement in the schematic file to set the version and date.
      # Any instance of %%version%% in the schematic gets replaced with the release version.
      # Any instance of %%date%% in the schematic gets replaced with the release date.
      - name: Set schematic version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: "hardware/*.kicad_sch"
          find: "%%version%%"
          replace: ${{ github.event.inputs.version }}

      - name: Set schematic date
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: "hardware/*.kicad_sch"
          find: "%%date%%"
          replace: ${{ steps.date.outputs.date }}

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the 1_pcb/.kibot/release.kibot.yaml folder.
      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@3acaa425740658045e0f1ecda7220e7dc6f7d2e3
        with:
          config: pcb/.kibot/schematic_outputs.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: hardware/${{ steps.project_name.outputs.project_name }}.kicad_sch
          board: hardware/${{ steps.project_name.outputs.project_name }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.project_name.outputs.project_name }}-${{ github.event.inputs.version }}-${{ steps.date.outputs.date }}
          path: ${{ env.OutputFolder }}/**
